[workspace]
authors = ["Nicholas A. Del Grosso <delgrosso.nick@gmail.com>"]
channels = ["conda-forge"]
name = "testPixiEnv"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]
build-kernel = "python -m ipykernel install --user --name napari"
launch_caimaging = "python launch_napari.py"
launch_atlas = "python launch_atlas.py"

[dependencies]
python = "3.13.*"
pip = ">=26.0.1,<27"
cvxpy = ">=1.8.2,<2"
portaudio = ">=19.7.0,<20"

[pypi-dependencies]
napari = { version = ">=0.7.0, <0.8", extras = ["all"] }
ipykernel = ">=6.31.0, <7"
qtpy = ">=2.4.3, <3"
pyocclient = ">=0.6, <0.7"
napari-owncloud = ">=0.1.2, <0.2"
numpy = ">=2.4.4, <3"
matplotlib = ">=3.10.8, <4"
seaborn = ">=0.13.2, <0.14"
brainglobe-atlasapi = ">=2.3.0, <3"
oasis-deconv = ">=0.2.1, <0.3"
sounddevice = ">=0.5.5, <0.6"
